# Generated by Django 3.0.6 on 2020-05-18 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200518_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
