# Generated by Django 3.0.6 on 2020-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200521_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='display_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product_review',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
